version: "3"

vars:
    PROJECT: nearness
    TESTS: tests

tasks:
    uv-sync:
        cmd: uv sync --all-extras

    uv-upgrade-dev:
        cmd: |
            uv add --dev notebook pytest pytest-html hypothesis coverage pytest-cov pytest-benchmark genbadge ruff pre-commit black pyright bandit

    pre-commit-install:
        cmd: uv run pre-commit install

    pre-commit-all:
        cmd: uv run pre-commit run --all-files

    lint:
        cmds:
            - uv run ruff check src/{{.PROJECT}}
            - uv run black --diff --check --config pyproject.toml src/{{.PROJECT}} {{.TESTS}}

    format:
        cmds:
            - uv run ruff check src/{{.PROJECT}} --fix
            - uv run black --config pyproject.toml src/{{.PROJECT}} {{.TESTS}}

    test:
        cmds:
            - uv run pytest -rsx -c pyproject.toml --cov=src/{{.PROJECT}} {{.TESTS}}
            - uv run genbadge coverage -i coverage.xml -o assets/coverage.svg

    typing:
        cmd: uv run pyright

    typing-quality:
        cmd: uv run pyright --ignoreexternal --verifytypes nearness

    safety:
        cmds:
            - uv run bandit -ll --recursive src/{{.PROJECT}} {{.TESTS}}

    check:
        cmds:
            - task: lint
            - task: typing
            - task: test
            - task: safety

    build:
        cmd: uv build

    publish:
        cmd: uv publish --skip-existing

    sysinfo:
        cmd: uv run python .github/system_info.py
